"O algoritmo dos k-vizinhos mais próximos é utilizado na classificação e também na regressão. Ele envolve observar os K-vizinhos mais próximos."
"Classificação = classificar em grupos."
"Regressão = adivinhar uma resposta (como um número)."
"Extrair características significa converter um item (como uma fruta ou um usuário) em uma lista de números que podem ser comparados."
"Escolher boas características é uma parte importante para que um algoritmo dos k-vizinhos mais próximos opere corretamente."
"O algoritmo dos k-vizinhos mais próximos é muito útil e é a sua introdução ao mundo mágico do aprendizado de máquina"